// Generated by gencpp from file light_robot/AddTwoNumRequest.msg
// DO NOT EDIT!


#ifndef LIGHT_ROBOT_MESSAGE_ADDTWONUMREQUEST_H
#define LIGHT_ROBOT_MESSAGE_ADDTWONUMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace light_robot
{
template <class ContainerAllocator>
struct AddTwoNumRequest_
{
  typedef AddTwoNumRequest_<ContainerAllocator> Type;

  AddTwoNumRequest_()
    : x(0)
    , y(0)  {
    }
  AddTwoNumRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::light_robot::AddTwoNumRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::light_robot::AddTwoNumRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoNumRequest_

typedef ::light_robot::AddTwoNumRequest_<std::allocator<void> > AddTwoNumRequest;

typedef boost::shared_ptr< ::light_robot::AddTwoNumRequest > AddTwoNumRequestPtr;
typedef boost::shared_ptr< ::light_robot::AddTwoNumRequest const> AddTwoNumRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::light_robot::AddTwoNumRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::light_robot::AddTwoNumRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::light_robot::AddTwoNumRequest_<ContainerAllocator1> & lhs, const ::light_robot::AddTwoNumRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::light_robot::AddTwoNumRequest_<ContainerAllocator1> & lhs, const ::light_robot::AddTwoNumRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace light_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::light_robot::AddTwoNumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::light_robot::AddTwoNumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_robot::AddTwoNumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_robot::AddTwoNumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot::AddTwoNumRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot::AddTwoNumRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::light_robot::AddTwoNumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b834ede922a0fff22c43585c533b49f";
  }

  static const char* value(const ::light_robot::AddTwoNumRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b834ede922a0fffULL;
  static const uint64_t static_value2 = 0x22c43585c533b49fULL;
};

template<class ContainerAllocator>
struct DataType< ::light_robot::AddTwoNumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "light_robot/AddTwoNumRequest";
  }

  static const char* value(const ::light_robot::AddTwoNumRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::light_robot::AddTwoNumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n"
"int64 y \n"
"\n"
;
  }

  static const char* value(const ::light_robot::AddTwoNumRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::light_robot::AddTwoNumRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoNumRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::light_robot::AddTwoNumRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::light_robot::AddTwoNumRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIGHT_ROBOT_MESSAGE_ADDTWONUMREQUEST_H
